sudo: false
dist: trusty

language: c++

git:
  submodules: true

services:
  - docker

env:
  global:
  - DOCKER_USERNAME=guillaumejacquenot
  - secure: "u4AM4AU5/O6i9LqUg8lBMXn4IrMOqvCP6Vdo70q09mpAKZ+Y8eeLhHmeyKJ3zO796C3E8yfjIw2XlfQvFies/54D1O9ihz2EoPo7kN/38qqrg5AwO+U893vrn8N4mty3HKjn++GOpd3V2OKc6WduNcJVeaCHSCpjpthaaOuJMuvlQHwpbfc3Li0o+7xMdK5r5g3rW7OfzfAnG56zW6balkiEs3K9L1NeBp7geJJ8avUEpzSHfRADgGf8DFBNP6ZP/9CdGGLQ9koTizHS/ysJG1CkT+s1vKpjUpj1bc+2xM1d0UpxbiRd13hpTj2G3RXPxHb/luzLkry8EapBGGO3Xby3CwDrRKnrLYzVkGR1X438huJi8/ratFs3QpAs8/hA6KEPO8GGCVJxAkLWlc4a7nEvczLggsFWKvDccNhjp5JSgUVOUbRMKkG8tPqK2+xWYmyQkBYvNPWhv1rKg3Azw1EA7+DXA2+XBzf2m1iC9hWLKQv/s7JBXafk7+G3dcm2KXe2LGKMgsbHhGVl15sNoEFoeWrAy7F0ELDI3jqwcRQno94ZV8boFPJEhgYpqpPtc7JG0aS/mquSX7cUH/wKk6Kn1DV3G9NzWDOOVKFvD9dDs0VYgzbbWWDkUI/0fcdAn+DM40ajCzSwHMRvbeQQux/hyLK4j/HS+YVSdpgxhPw="
  - secure: "lSX31RH24XIeWXIrXbvY6Gyzr4XYccjL/cnQI5jY8k2qq74S4aiRv9rUqh8JHX4uu3x2t3+S6iYNFFkBRdrGKelGNOu9hmibNiQ7I8+z9j7sAMqVMYxeIsmtlKvXePpuZe3p2QBIvx2aqfsy64ReYuaMOjgEKA1SnGiR+C8qVjbOF0ATyDWxbLVEqR6G9dSQkuKm63mCe5Bvn6JrvU2s5rzqGS4nJVWMVrh0R/PNCKQKzWaY2bwnnB+w+OzoOyoVln4IYh5BmNlbnQoMdLEKeNOYWK6g+VemtYJZlwOT26rM2pM2AJ9apDF11WSwQsX+YC5xfqX6x9pkldS3EcZ9d2o6bXe0tct1MUeS09jU0uCei2ucM4H90t1DgIEbgDSxg2Of2Jwrw7rwNoehbC1pFciovjgQt/UmgwCv+w04J2L7/1eRWyMiBiNlr/nrKryBqAvmGDinLoAPXaCFPuJqcc0ok8v6H42V6mZ6e5oj3TkG3Jfk2mm2v2K3Dharjs67YsYwrl+puCRcamgdej4thK9VM68DKgUxNe7Z9f/SR0EhS6eNAlFyK7NvTmVQBj9J/IWZmHXu6IPblIXmExY7cgTmyJ51dLDIqIBNjz2zjnihTY9rs6Xqb+7hWjWLI8xhRLgYsuueR3QTy7TNk5n8Id6UF2zUJP/rWU8R7UjWYn8="

matrix:
  include:
    - name: "Debian 9 release GCC 6"
      env:
        - TARGET=debian_9_release_gcc_6
    - name: "Debian 10 release GCC 8"
      env:
        - TARGET=debian_10_release_gcc_8
    - name: "Debian 10 coverage GCC 8"
      env:
        - TARGET=debian_10_coverage_gcc_8
    - name: "Windows cross compilation Gcc X PosixThreads release"
      env:
        - TARGET=windows_gccx_posix

before_install:
  - echo "A 'docker pull' command will be performed with the script section"

script:
  - make $TARGET
  - if [ "$TARGET" == "debian_10_release_gcc_8" ];
    then
    echo "Generate documentation";
    make doc;
    cp doc.html xdyn_doc_user.html;
    mkdir -p public && cp doc.html public/index.html;
    fi
  - if [ "$TARGET" == "debian_10_release_gcc_8" ];
    then
    echo "Create xdyn docker container";
    cp build_deb10/xdyn.deb .;
    docker build --tag xdyn .;
    fi
  - if [ "$TARGET" == "debian_10_release_gcc_8" ];
    then
    echo "Create xdyn grpc force model docker container";
    make docker_grpc_force_model;
    echo "Create xdyn grpc waves model docker container";
    make docker_grpc_waves_model;
    fi

after_success:
- |
    echo "TRAVIS_BRANCH  $TRAVIS_BRANCH"
    echo "TRAVIS_TAG     $TRAVIS_TAG"
    echo "TARGET         $TARGET"
- if [ "$TRAVIS_TAG" ] && [ "$TARGET" == "debian_10_release_gcc_8" ];
  then
  echo "Pushing xdyn docker image to dockerhub";
  docker images;
  docker tag xweave sirehna/xweave;
  docker tag xdyn sirehna/xdyn;
  docker tag xdyn-force-grpc:python3 sirehna/xdyn-force-grpc:python3;
  docker tag xdyn-waves-grpc:python3 sirehna/xdyn-waves-grpc:python3;
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
  docker push sirehna/xdyn;
  docker push sirehna/xweave;
  docker push sirehna/xdyn-force-grpc:python3;
  docker push sirehna/xdyn-waves-grpc:python3;
  fi
- if [ "$TRAVIS_TAG" ] && [ "$TARGET" == "debian_9_release_gcc_6" ];
  then
  echo "Fetching generated deb";
  ls -altr build_deb9/xdyn.deb;
  shasum -a256 build_deb9/xdyn.deb;
  cp build_deb9/xdyn.deb xdyn_binary_debian9_amd64.deb;
  fi
- if [ "$TRAVIS_TAG" ] && [ "$TARGET" == "debian_10_release_gcc_8" ];
  then
  echo "Fetching generated deb";
  ls -altr build_deb10/xdyn.deb;
  shasum -a256 build_deb10/xdyn.deb;
  cp build_deb10/xdyn.deb xdyn_binary_debian10_amd64.deb;
  fi
- if [ "$TRAVIS_TAG" ] && [ "$TARGET" == "windows_gccx_posix" ];
  then
  echo "Fetching generated zip";
  ls -altr build_win_posix/xdyn.zip;
  shasum -a256 build_win_posix/xdyn.zip;
  cp build_win_posix/xdyn.zip xdyn_binary_windows_64_posixthread.zip;
  fi

# travis setup releases
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
before_deploy:
- ls -altr xdyn_binary_* || true;
- ls -altr xdyn_doc_user* || true;
# - ls -altr xdyn_binary_debian8_amd64.deb;
# - ls -altr xdyn_binary_windows_64.zip;
deploy:
- provider: releases
  api_key:
    secure: FjoYH/qo1sFqUdZ+SbBrE5dH3qzNKAYGh167TZKv3JicS3OLoFbz3OS96QNYg/IUwg60PPDqxY35LUyxxw72CCvCcGQbbacJBA3K4mtcyxofYKFmh4OifKrP2lqSOzp3KY3W7hL49PIwrNYEychiZ5cCXWWoanD+4tgiSXfkaQ9ZtGt2a6mw2zRl/aOmK0Yx19IJP3+J+fV5DZouMj7XuSZ2w8ETVl1XvdytKWOb1mDPsvUBNFA/sfdv5LldQLL5hKh6q457dK9+oJ8iGpekm6Gau0HpcMFIzRXDikDqCMmHA8NalIlhTc45291W5O3j1xMj4HSzhHCdBzzVyjgOQSJpNVzWpbb8TmmgRYhNHkGz9uLW0ggdGlL+s1rIzmc193YQuJuEiNp9ud7xUucuA4TT9YNslCukYu6D6Q7fVVtitOQm72nhPML0FoUMJdOfy+PJFgV4Tu8/xne4ilqDqu9m3AQBX0tgqWpnk/LPXbCj1VYypWHEg0y8EjjeBPc08FTmyOmwZQnjMB0Ibg1stkUNyaZkyUPFNbLxRjKMCAar7eif+rGhW2TP3IHyZcAs9obcXWWlqNYidF5ul1XJ3Wht0DKaw4Tbji3Rktzu1BelcDVVCPoGbyli5pW7YpfR9yueWaaMNEl0JZMij/cF1uxDfm7OyBcXUOrxDoTS4II=
  skip_cleanup: true
  file_glob: true
  file:
    - xdyn_binary_*
    - xdyn_doc_user*
  #file:
  #  - xdyn_binary_debian8_amd64.deb
  #  - xdyn_binary_windows_64.zip
  on:
    tags: true
    repo: sirehna/xdyn
    branch: master
- provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    tags: true
    repo: sirehna/xdyn
    branch: master
    condition: $TARGET = debian_9_release_gcc_6
